### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by kenan3008** [OpenIdentityPlatform/OpenDJ#106]
**Describe the bug**
Executing `./status` or `/.dsreplication status` gives out the following error:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Expected behavior**
No error is shown

OpenDJ version is 4.4.4

**Comment by maximthomas** [comment]
@kenan3008, This message is not critical and does not affect anything. OpenDJ client utils use `java.util.logging` instead `slf4j`.

**Comment by InterstellarScout** [comment]
@maximthomas I have this same issue. Along with that, when I have a critical issue that outputs a log like this:
`
See /tmp/opendj-setup-8466243813533921465.log for a detailed log of the failed
operation.
`
That log file is empty. No logging has occurred. Is there a solution?

**Comment by maximthomas** [comment]
@InterstellarScout what command are you trying to execute?

**Comment by InterstellarScout** [comment]
@maximthomas When that setup log gets created, it fails when it attempts to create the base dn. 
`
./setup -h localhost -p 38901 --ldapsPort 48901 --adminConnectorPort 4444 --enableStartTLS --generateSelfSignedCertificate --rootUserDN "cn=OpenDJAdmin" --rootUserPassword password --baseDN "dc=example,dc=com" --addBaseEntry --cli --acceptLicense --no-prompt 
`
Which spits out 
`
Error Creating Base Entry.
See /tmp/opendj-setup-8289093158414612040.log for a detailed log of the failed
operation.
Please report this error and provide the log file mentioned above.
`
Note that blah.log is empty, so I have no way to troubleshoot. 
All subsequent attempts to ldapsearch or create entries fail with ldif fail since there is no baseDN.

**Comment by mario-ragucci-sp** [comment]
> @maximthomas When that setup log gets created, it fails when it attempts to create the base dn.
> `./setup -h localhost -p 38901 --ldapsPort 48901 --adminConnectorPort 4444 --enableStartTLS --generateSelfSignedCertificate --rootUserDN "cn=OpenDJAdmin" --rootUserPassword password --baseDN "dc=example,dc=com" --addBaseEntry --cli --acceptLicense --no-prompt `
> Which spits out
> `Error Creating Base Entry. See /tmp/opendj-setup-8289093158414612040.log for a detailed log of the failed operation. Please report this error and provide the log file mentioned above.`
> Note that blah.log is empty, so I have no way to troubleshoot.
> All subsequent attempts to ldapsearch or create entries fail with ldif fail since there is no baseDN. It's worth noting that whether I attempt to create the baseDN through a single line command or the setup cli, it still fails, and reports an empty file.

got the same issue here. Creating the base entry fails, and the logfile is empty. At least, the base entry can be created with a prior version of OpenDJ (4.4.1 worked for me), but still, this is pretty annoying right now. 

Please fix the logging, thanks

**Comment by maximthomas** [comment]
see #123
