### ISSUE TITLE
GenericJMXConfValue: Cannot convert list of objects to numbers.

### ISSUE THREAD

**Issue by jbgorski** [OpenIdentityPlatform/OpenDJ#293]
**Describe the bug**
Hello,
When I try to gather OpenDJ JMX metrics by using collectd I recieve the following error: 
Aug 01 10:17:25 ip-xx-xxx-xx-xxx collectd[27469]: GenericJMXConfValue: Cannot convert list of objects to numbers.
My guess is that the reason is type of MBean Attribute which for all metrics are java.lang.String
Have you encountered such a problem?
Why does OpenDJ expose numeric metric as java.lang.String ?

**To Reproduce**
Setup collectd with Opendj. The example collectd configuration file at attachment

**Expected behavior**
OpenDJ should expose JMX metrics by using proper Java types. Numeric values can be exposed for instance by using java.lang.Long

**Comment by jbgorski** [comment]
[collectd.conf.txt](https://github.com/OpenIdentityPlatform/OpenDJ/files/12228429/collectd.conf.txt)

**Comment by maximthomas** [comment]
@jbgorski 
Hello, could you please provide more info? Which metric is supposed to be numeric, but OpenDJ returns it as a string?

**Comment by jbgorski** [comment]
I am sending few examples below

<html>
<head>
	
	
	
</head>

<body>


Object Name | Attribute
-- | --
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-Disk_Space_Monitor,Rdn3=cn-userRoot_backend | disk-free
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-JMX_Connection_Handler_1689 | ds-connectionhandler-num-connections
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-Work_Queue | All attributes
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-adminRoot_Backend | ds-backend-entry-count
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-JVM_Memory_Usage | All attributes
org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-Entry_Caches | All attributes


</body>

</html>

**Comment by yurem** [comment]
The issue caused by wrong value which this method returns: `https://github.com/OpenIdentityPlatform/OpenDJ/blob/ea2cd6448b3838254ada8804b5a8d8f87bcef226/opendj-server-legacy/src/main/java/org/opends/server/config/JMXMBean.java#L376` it should return native type instead of Attribute.

collectd GenericJMXConfValue.java correctly can handle String type according to the code: https://github.com/collectd/collectd/blob/ef1e157de1a4f2cff10f6f902002066d0998232c/bindings/java/org/collectd/java/GenericJMXConfValue.java#L90
